config/routes.rb
Uchoos::Application.routes.draw do
  
  devise_for :users

  resources :scenes
  resources :stories
  resources :users

  get "director/route"

    
  match 'stories/:story_id/scenes/new' => 'scenes#new'
  
  match 'director/router/:story/:scene' => 'director#router'
  match 'director/choice/:story/:scene' => 'director#render_choice'
  match 'director/set_sms' => 'director#set_sms'
  match 'director/story_menu' => 'director#story_menu'
  
  match 'api/twilio/voice' => 'api#twilio_voice'
  match 'api/twilio/sms' => 'api#twilio_sms'

  root :to => "users#index"

end

app/models/scene.rb
class Scene < ActiveRecord::Base
  
  belongs_to :story
  
  def choiceless?
    self.option_two == nil && !self.option_one.blank?
  end
  
  def final?
    self.option_two == nil && self.option_one == nil
  end
  
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  # GET /scenes
  # GET /scenes.xml
  def index
    @scenes = Scene.find(:all, :order => "id ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scenes }
    end
  end

  # GET /scenes/1
  # GET /scenes/1.xml
  def show
    @scene = Scene.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @scene }
    end
  end

  # GET /scenes/new
  # GET /scenes/new.xml
  def new
    @scene = Scene.new
    @scene.story_id = params[:story_id]

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scene }
    end
  end

  # GET /scenes/1/edit
  def edit
    @scene = Scene.find(params[:id])
    @story = Story.find_by_id(@scene.story_id)
  end

  # POST /scenes
  # POST /scenes.xml
  def create
    @scene = Scene.new(params[:scene])
    story = @scene.story_id

    respond_to do |format|
      if @scene.save
        format.html { redirect_to("/stories/#{story.to_s}", :notice => 'Scene was successfully created.') }
        format.xml  { render :xml => @scene, :status => :created, :location => @scene }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @scene.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scenes/1
  # PUT /scenes/1.xml
  def update
    @scene = Scene.find(params[:id])

    respond_to do |format|
      if @scene.update_attributes(params[:scene])
        format.html { redirect_to(@scene, :notice => 'Scene was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @scene.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scenes/1
  # DELETE /scenes/1.xml
  def destroy
    @scene = Scene.find(params[:id])
    story = @scene.story_id
    @scene.destroy


    respond_to do |format|
      format.html { redirect_to("/stories/#{story.to_s}", :notice => 'Scene was successfully deleted.') }
      format.xml  { head :ok }
    end
  end
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/scenes/_form.html.erb
<%= form_for(@scene) do |f| %>
  <% if @scene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scene.errors.count, "error") %> prohibited this scene from being saved:</h2>

      <ul>
      <% @scene.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag('scene[story_id]', @scene.story_id) %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :scene_text %><br />
    <%= text_area(:scene, :scene_text, :size => "66x20") %>
  </div>
  <div class="field">
    <%= f.label :scene_audio %><br />
    <%= text_field(:scene, :scene_audio, :size => "92x3") %>
  </div>
  <div class="field">
    <%= f.label :choice_text %><br />
    <%= text_area(:scene, :choice_text, :size => "66x5") %>
  </div>
  <div class="field">
    <%= f.label :choice_audio %><br />
    <%= text_field(:scene, :choice_audio, :size => "92x3") %>
  </div>
  <div class="field">
    <%= f.label :option_one %><br />
	<% if @story %>
    <%= select("scene", "option_one", @story.scenes.all.collect {|s| [ s.name, s.id ] }, { :prompt => "select scene" })%>
	<% else %>
	<%=	select("scene", "option_one", ["no scenes available"]) %>
	<% end %>
	
  </div>
  <div class="field">
    <%= f.label :option_two %><br />
	<% if @story %>
    <%= select("scene", "option_two", @story.scenes.all.collect {|s| [ s.name, s.id ] }, { :prompt => "select scene" })%>
	<% else %>
	<%=	select("scene", "option_one", ["no scenes available"]) %>
	<% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scenes/edit.html.erb
<h1>Editing scene</h1>

<%= render 'form' %>

<%= link_to 'Show', @scene %> |
<%= link_to 'Back', scenes_path %>

app/views/scenes/index.html.erb
<h1>Listing scenes</h1>

<hr />

<% @scenes.each do |scene| %>
<div id="story">
    <p><strong><%= scene.name %></strong> (<%= link_to 'audio', scene.scene_audio %>) <br />
	<%= scene.scene_text %></p>
	<p><strong>Choice</strong> (<%= link_to 'audio', scene.choice_audio %>) <br />
	<%= scene.choice_text %></p>
    Option one: <%= scene.option_one %> | 
    Option two: <%= scene.option_two %> | 
    <%= link_to 'Show', scene %></td> |
    <%= link_to 'Edit', edit_scene_path(scene) %> |
    <%= link_to 'Destroy', scene, :confirm => 'Are you sure?', :method => :delete %>
	<hr />
<% end %>

app/views/scenes/new.html.erb
<h1>New scene</h1>

<%= render 'form' %>

<%= link_to 'Back', scenes_path %>

app/views/scenes/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <%= @scene.story.name %>
</h3>

<p>
  <b>Scene:</b>
  <%= @scene.name %>
</p>

<p>
  <b>Scene text:</b>
  <%= @scene.scene_text %>
</p>

<p>
  <b>Order:</b>
  <%= @scene.order %>
</p>

<p>
  <b>Scene audio:</b> 
  <%= link_to_unless(@scene.scene_audio.nil?, "(link)", @scene.scene_audio) %>
</p>

<p>
  <b>Choice text:</b>
  <%= @scene.choice_text %>
</p>

<p>
  <b>Choice audio:</b>
  <%= link_to_unless(@scene.choice_audio.nil?, "(link)", @scene.choice_audio) %>
</p>

<p>
  <b>Option one:</b>
  <%= @scene.option_one %>
</p>

<p>
  <b>Option two:</b>
  <%= @scene.option_two %>
</p>


<%= link_to 'Edit', edit_scene_path(@scene) %> |
<%= link_to 'Back', scenes_path %>