config/routes.rb
Uchoos::Application.routes.draw do
  
  devise_for :users

  resources :scenes
  resources :stories
  resources :users

  get "director/route"

    
  match 'stories/:story_id/scenes/new' => 'scenes#new'
  
  match 'director/router/:story/:scene' => 'director#router'
  match 'director/choice/:story/:scene' => 'director#render_choice'
  match 'director/set_sms' => 'director#set_sms'
  match 'director/story_menu' => 'director#story_menu'
  
  match 'api/twilio/voice' => 'api#twilio_voice'
  match 'api/twilio/sms' => 'api#twilio_sms'

  root :to => "users#index"

end

app/models/story.rb
class Story < ActiveRecord::Base
  
  belongs_to :user
  has_many :scenes, :order => "id ASC"
  
  validates_uniqueness_of :keyword, :name
  validates_presence_of :keyword, :name  
    
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  # GET /stories
  # GET /stories.xml
  def index
    @stories = Story.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.xml
  def show
    @story = Story.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @story }
    end
  end

  # GET /stories/new
  # GET /stories/new.xml
  def new
    @story = Story.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.xml
  def create
    @story = Story.new(params[:story])
    @story.user_id = current_user.id

    respond_to do |format|
      if @story.save
        format.html { redirect_to(@story, :notice => 'Story was successfully created.') }
        format.xml  { render :xml => @story, :status => :created, :location => @story }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.xml
  def update
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.update_attributes(params[:story])
        format.html { redirect_to(@story, :notice => 'Story was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @story.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.xml
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    respond_to do |format|
      format.html { redirect_to(stories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :keyword %><br />
    <%= f.text_field :keyword %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= text_field(:story, :name, :size => "92x3") %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= text_area(:story, :description, :size => "66x5") %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h3>Listing stories</h3>

<% if current_user %>
<%= link_to 'New Story', new_story_path %>
<% else %>
<p>Sign in to create a story</p>
<% end %>

<br /> <hr />

<% @stories.each do |story| %>

 <div id="story">
	<%= link_to "#{story.name}", story %><%=  %> (<%= story.keyword %>) by
	<% if story.user.name %>
	<td><%= story.user.name %></td>
	<% else %>
    <td><%= story.user_id %></td>
	<% end %>
	| <%= story.active %> | 
	<% if story.scenes %>
	Scenes (<%= story.scenes.size %>)
	<% else %>
	No scenes yet
	<% end %>
	<p><strong>Description:</strong> <%= story.description %></p>
    <%= link_to 'Edit', edit_story_path(story) %> |
    <%= link_to 'Destroy', story, :confirm => 'Are you sure?', :method => :delete %>
	<br /> <hr />
<% end %>
</div>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>


  <h3><%= @story.name %></h3>
<p>by 
<% if @story.user.name %>
<%= @story.user.name %>
<% end %> 
</p>

<p>
  <b>Description:</b>
  <%= @story.description %>
</p>

<p>
  <b>Keyword:</b>
  <%= @story.keyword %> |  
<b>Active:</b>
  <%= @story.active %>
</p>

<p>
  <%= button_to "Add Scene", "#{@story.id}/scenes/new" %>
</p>

	<table>
	  <tr>
		<th>Sc. #</th>
		<th>Title</th>
		<th>Choice 1</th>
		<th>Choice 2</th>
		<th></th>
		<th></th>
	  </tr>

	<% @story.scenes.each_with_index do |scene, count| %>
	  <tr class="<%= cycle("even", "odd") %>">
		<td><%= count + 1 %></td>
		<td><%= link_to scene.name, scene %></td>
		<td><%= scene.option_one %></td>
		<td><%= scene.option_two %></td>
		<td><%= link_to 'Edit', edit_scene_path(scene) %></td>
		<td><%= link_to 'X', scene, :confirm => 'Are you sure?', :method => :delete %></td>	  
	  </tr>
	<% end %>
	</table>


<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>